# name: Validate Production Pull Request

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'force-app/**'

# jobs:
#   validate:
#     runs-on: ubuntu-latest
#     steps:
#       # Step 1: Set up Node (needed for sfdx CLI)
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18'

#       # Step 2: Checkout source code
#       - uses: actions/checkout@v3

#       # Step 3: Install Salesforce CLI
#       - name: Install sfdx
#         run: npm install @salesforce/cli --global

#       # Step 4: Authenticate with JWT
#       - name: Authenticate with Salesforce
#         run: |
#           echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
#           sf org login jwt \
#             --username "${{ secrets.DEPLOYMENT_USER_NAME }}" \
#             --jwt-key-file server.key \
#             --client-id "${{ secrets.CONSUMER_KEY }}" \
#             --instance-url ${{ vars.INSTANCE_URL }} \
#             --set-default

#       # Step 5: Validate Deployment (Dry Run)
#       - name: Validate on Production
#         run: |
#           sf project deploy start \
#             --target-org default \
#             --test-level RunLocalTests \
#             --dry-run
